include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - require_trailing_commas
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - prefer_relative_imports
    - unawaited_futures
