// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmAn2qjdNd_iyCS4wqYniDj6m9bO5Aqc',
    appId: '1:853397289334:web:a7e127f9c0d67637786257',
    messagingSenderId: '853397289334',
    projectId: 'moveit-v2-e8079',
    authDomain: 'moveit-v2-e8079.firebaseapp.com',
    storageBucket: 'moveit-v2-e8079.firebasestorage.app',
    measurementId: 'G-7J8C632N8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFevEfWcze2xI3fZaixje41ABpQ0o4flo',
    appId: '1:853397289334:android:114cfc3e48e64121786257',
    messagingSenderId: '853397289334',
    projectId: 'moveit-v2-e8079',
    storageBucket: 'moveit-v2-e8079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLnd3NMmaposfxaPxOIcb2MioC3asu9E',
    appId: '1:853397289334:ios:ef95df50964c66c0786257',
    messagingSenderId: '853397289334',
    projectId: 'moveit-v2-e8079',
    storageBucket: 'moveit-v2-e8079.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );
}
